name: Static Tests

on:
    push:
        branches:
            - main
    pull_request:
    release:

jobs:
    composer-validate:
        name: Validate composer.json
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Validate
                run: composer validate --strict

    php-cs-fixer:
        name: PHP-CS-Fixer
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.1'
                    tools: php-cs-fixer

            -   name: Run PHP-CS-Fixer
                run: php-cs-fixer fix --dry-run --diff
    rector:
        name: Rector PHP Source
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.1'

            -   name: Install Dependencies
                run: composer install -d $GITHUB_WORKSPACE/tools/rector --prefer-dist --no-progress

            -   name: Analyse With Rector
                run: $GITHUB_WORKSPACE/tools/rector/vendor/bin/rector process --dry-run -vvv
